# Generated by Django 5.2 on 2025-04-26 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='updated_profile',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
