# Generated by Django 5.2 on 2025-04-26 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorms', '0002_alter_user_updated_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='updated_profile',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
