# Generated by Django 5.2 on 2025-05-29 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorms', '0006_room_description_room_image_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.ImageField(null=True, upload_to='static/rooms/%Y/%m'),
        ),
    ]
